#ifndef MICROPY_INCLUDED_MY_ESP32S3_VISION_MPCONFIGBOARD_H
#define MICROPY_INCLUDED_MY_ESP32S3_VISION_MPCONFIGBOARD_H

#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "MY_ESP32S3_VISION"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32S3"
#endif

#define MICROPY_HW_USB_MANUFACTURER_STRING "ESP-VISION"
#define MICROPY_HW_USB_PRODUCT_FS_STRING "MY_ESP32S3_VISION MicroPython"
#define MICROPY_HW_ENABLE_USBDEV (0)
#define MICROPY_HW_USB_CDC (0)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG (0)
#define MICROPY_HW_ENABLE_USB_RUNTIME_DEVICE (0)
#define MICROPY_HW_ENABLE_UART_REPL (1)

#define MICROPY_PY_ESPNOW (0)
#define MICROPY_HW_ENABLE_SDCARD (0)
#define MICROPY_PY_BLUETOOTH (0)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN (1)
#endif

// I2C0 - shared bus for Camera(SCCB) + ES8311 + FT5x06
#define MICROPY_HW_I2C0_SCL (48)
#define MICROPY_HW_I2C0_SDA (38)

#ifndef traceISR_EXIT_TO_SCHEDULER
#define traceISR_EXIT_TO_SCHEDULER()
#endif

#endif // MICROPY_INCLUDED_MY_ESP32S3_VISION_MPCONFIGBOARD_H